//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.Resources
{
    using System;
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This partial class was auto-generated by the StronglyTypedResourceBuilder
    // partial class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Exceptions
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions()
        {
        }
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("$safeprojectname$.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
  

        
        /// <summary>
        /// Create the appropriate type of exception from an hresult using the specified message
        /// </summary>
        public static bool TryCreateException(int hResult, string message, out System.Exception exception)
        {
            switch (unchecked((uint)hResult))
            {
                case 0xe1000001U: exception = $safeprojectname$.Resources.ServiceStartException.Create(hResult, message); return true;
                case 0xa1000005U: exception = $safeprojectname$.Resources.ServiceStopException.Create(hResult, message); return true;
                case 0xe1000006U: exception = $safeprojectname$.Resources.ServiceContinueException.Create(hResult, message); return true;
                case 0xe1000007U: exception = $safeprojectname$.Resources.ServicePauseException.Create(hResult, message); return true;
                case 0xe1000008U: exception = $safeprojectname$.Resources.ServiceCommandException.Create(hResult, message); return true;
                case 0xe100000bU: exception = $safeprojectname$.Resources.UnhandledException.Create(hResult, message); return true;
                default: exception = null; return false;
            }
        }
        
        /// <summary>
        /// The the event log facility id of events defined in this resource file
        /// </summary>
        internal static readonly int EventFacilityId = 256;
        
        /// <summary>
        /// The category id used to write events for this resource file
        /// </summary>
        internal static readonly int EventCategoryId = 2;
        
        /// <summary>
        /// The the event log used to write events for this resource file
        /// </summary>
        internal static readonly string EventLogName = "$safeprojectname$";
        
        /// <summary>
        /// The event source used to write events
        /// </summary>
        internal static readonly string EventSourceName = "$safeprojectname$";
        
        /// <summary>
        /// Writes an event log for the specified message id and arguments
        /// </summary>
        internal static void WriteEvent(string eventLog, string eventSource, int category, System.Diagnostics.EventLogEntryType eventType, long eventId, object[] arguments, System.Exception error)
        {
            try
            {
                EventLogging.WriteEvent(eventLog, eventSource, category, eventType, eventId, arguments, error);
            }
            catch { }
        }
        
        /// <summary>
        /// Returns the raw exception strings.
        /// </summary>
        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("CSharpTest.Net.Generators", "1.11.924.348")]
        public static partial class ExceptionStrings
        {
            /// <summary>
            /// Formats a message for an exception
            /// </summary>
            internal static string SafeFormat(string message, params object[] args)
            {
                try
                {
                    return string.Format(resourceCulture, message, args);
                }
                catch
                {
                    return message ?? string.Empty;
                }
            }
            /// <summary>
            /// http://example.com/?HResult={0:x8}
            /// </summary>
            internal static string HelpLinkFormat(int hResult, string typeName)
            {
                return SafeFormat("http://example.com/?HResult={0:x8}", hResult, typeName);
            }
            /// <summary>
            /// The service {0} failed to start.
            /// </summary>
            public static string ServiceStartException_string_ServiceName_ { get { return ResourceManager.GetString("ServiceStartException(string ServiceName)", resourceCulture); } }
            /// <summary>
            /// The service {0} failed to stop correctly.
            /// </summary>
            public static string ServiceStopException_string_ServiceName_ { get { return ResourceManager.GetString("ServiceStopException(string ServiceName)", resourceCulture); } }
            /// <summary>
            /// The service {0} failed to resume correctly.
            /// </summary>
            public static string ServiceContinueException_string_ServiceName_ { get { return ResourceManager.GetString("ServiceContinueException(string ServiceName)", resourceCulture); } }
            /// <summary>
            /// The service {0} failed to pause correctly.
            /// </summary>
            public static string ServicePauseException_string_ServiceName_ { get { return ResourceManager.GetString("ServicePauseException(string ServiceName)", resourceCulture); } }
            /// <summary>
            /// The service {0} failed to process command #{1}.
            /// </summary>
            public static string ServiceCommandException_string_ServiceName__int_CommandId_ { get { return ResourceManager.GetString("ServiceCommandException(string ServiceName, int CommandId)", resourceCulture); } }
            /// <summary>
            /// Unhandled exception: {0}
            /// </summary>
            public static string UnhandledException_string_message_ { get { return ResourceManager.GetString("UnhandledException(string message)", resourceCulture); } }
        }
    
     }

    /// <summary>
    /// Exception class: ServiceStartException
    /// The service {0} failed to start.
    /// </summary>
    [System.SerializableAttribute()]
    [global::System.Diagnostics.DebuggerStepThroughAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("CSharpTest.Net.Generators", "1.11.924.348")]
    public sealed partial class ServiceStartException : System.ApplicationException
    {
        /// <summary>
        /// Serialization constructor
        /// </summary>
        internal ServiceStartException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
        {
        }
        /// <summary>
        /// Used to create this exception from an hresult and message bypassing the message formatting
        /// </summary>
        internal static System.Exception Create(int hResult, string message)
        {
            return new ServiceStartException((System.Exception)null, hResult, message);
        }
        /// <summary>
        /// Constructs the exception from an hresult and message bypassing the message formatting
        /// </summary>
        private ServiceStartException(System.Exception innerException, int hResult, string message) : base(message, innerException)
        {
            base.HResult = hResult;
            base.HelpLink = $safeprojectname$.Resources.Exceptions.ExceptionStrings.HelpLinkFormat(HResult, GetType().FullName);
        }
        
        /// <summary>
        /// The serviceName parameter passed to the constructor
        /// </summary>
        public string ServiceName { get { if (Data["ServiceName"] is string) return (string)Data["ServiceName"]; else return default(string); } }
        
        /// <summary>
        /// The service {0} failed to start.
        /// </summary>
        public ServiceStartException(string serviceName)
        	: this((System.Exception)null, unchecked((int)0xE1000001U), $safeprojectname$.Resources.Exceptions.ExceptionStrings.SafeFormat($safeprojectname$.Resources.Exceptions.ExceptionStrings.ServiceStartException_string_ServiceName_, serviceName))
        {
            base.Data["ServiceName"] = serviceName;
            WriteEvent(serviceName);
        }
        /// <summary>
        /// The service {0} failed to start.
        /// </summary>
        public ServiceStartException(string serviceName, System.Exception innerException)
        	: this(innerException, unchecked((int)0xE1000001U), $safeprojectname$.Resources.Exceptions.ExceptionStrings.SafeFormat($safeprojectname$.Resources.Exceptions.ExceptionStrings.ServiceStartException_string_ServiceName_, serviceName))
        {
            base.Data["ServiceName"] = serviceName;
            WriteEvent(serviceName);
        }
        /// <summary>
        /// Prepares the arguments as strings and writes the event
        /// </summary>
        private void WriteEvent(string serviceName)
        {
            string[] ctorEventArguments = new string[] {
            $safeprojectname$.Resources.Exceptions.ExceptionStrings.SafeFormat(@"{0}", serviceName),
            };
            $safeprojectname$.Resources.Exceptions.WriteEvent(
                $safeprojectname$.Resources.Exceptions.EventLogName,
                $safeprojectname$.Resources.Exceptions.EventSourceName,
                $safeprojectname$.Resources.Exceptions.EventCategoryId,
                System.Diagnostics.EventLogEntryType.Error,
                0x0C1000001L, ctorEventArguments, this);
        }
        /// <summary>
        /// if(condition == false) throws The service {0} failed to start.
        /// </summary>
        public static void Assert(bool condition, string serviceName)
        {
            if (!condition) throw new ServiceStartException(serviceName);
        }
    }
    /// <summary>
    /// Exception class: ServiceStopException
    /// The service {0} failed to stop correctly.
    /// </summary>
    [System.SerializableAttribute()]
    [global::System.Diagnostics.DebuggerStepThroughAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("CSharpTest.Net.Generators", "1.11.924.348")]
    public sealed partial class ServiceStopException : System.ApplicationException
    {
        /// <summary>
        /// Serialization constructor
        /// </summary>
        internal ServiceStopException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
        {
        }
        /// <summary>
        /// Used to create this exception from an hresult and message bypassing the message formatting
        /// </summary>
        internal static System.Exception Create(int hResult, string message)
        {
            return new ServiceStopException((System.Exception)null, hResult, message);
        }
        /// <summary>
        /// Constructs the exception from an hresult and message bypassing the message formatting
        /// </summary>
        private ServiceStopException(System.Exception innerException, int hResult, string message) : base(message, innerException)
        {
            base.HResult = hResult;
            base.HelpLink = $safeprojectname$.Resources.Exceptions.ExceptionStrings.HelpLinkFormat(HResult, GetType().FullName);
        }
        
        /// <summary>
        /// The serviceName parameter passed to the constructor
        /// </summary>
        public string ServiceName { get { if (Data["ServiceName"] is string) return (string)Data["ServiceName"]; else return default(string); } }
        
        /// <summary>
        /// The service {0} failed to stop correctly.
        /// </summary>
        public ServiceStopException(string serviceName)
        	: this((System.Exception)null, unchecked((int)0xA1000005U), $safeprojectname$.Resources.Exceptions.ExceptionStrings.SafeFormat($safeprojectname$.Resources.Exceptions.ExceptionStrings.ServiceStopException_string_ServiceName_, serviceName))
        {
            base.Data["ServiceName"] = serviceName;
            WriteEvent(serviceName);
        }
        /// <summary>
        /// The service {0} failed to stop correctly.
        /// </summary>
        public ServiceStopException(string serviceName, System.Exception innerException)
        	: this(innerException, unchecked((int)0xA1000005U), $safeprojectname$.Resources.Exceptions.ExceptionStrings.SafeFormat($safeprojectname$.Resources.Exceptions.ExceptionStrings.ServiceStopException_string_ServiceName_, serviceName))
        {
            base.Data["ServiceName"] = serviceName;
            WriteEvent(serviceName);
        }
        /// <summary>
        /// Prepares the arguments as strings and writes the event
        /// </summary>
        private void WriteEvent(string serviceName)
        {
            string[] ctorEventArguments = new string[] {
            $safeprojectname$.Resources.Exceptions.ExceptionStrings.SafeFormat(@"{0}", serviceName),
            };
            $safeprojectname$.Resources.Exceptions.WriteEvent(
                $safeprojectname$.Resources.Exceptions.EventLogName,
                $safeprojectname$.Resources.Exceptions.EventSourceName,
                $safeprojectname$.Resources.Exceptions.EventCategoryId,
                System.Diagnostics.EventLogEntryType.Warning,
                0x081000005L, ctorEventArguments, this);
        }
        /// <summary>
        /// if(condition == false) throws The service {0} failed to stop correctly.
        /// </summary>
        public static void Assert(bool condition, string serviceName)
        {
            if (!condition) throw new ServiceStopException(serviceName);
        }
    }
    /// <summary>
    /// Exception class: ServiceContinueException
    /// The service {0} failed to resume correctly.
    /// </summary>
    [System.SerializableAttribute()]
    [global::System.Diagnostics.DebuggerStepThroughAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("CSharpTest.Net.Generators", "1.11.924.348")]
    public sealed partial class ServiceContinueException : System.ApplicationException
    {
        /// <summary>
        /// Serialization constructor
        /// </summary>
        internal ServiceContinueException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
        {
        }
        /// <summary>
        /// Used to create this exception from an hresult and message bypassing the message formatting
        /// </summary>
        internal static System.Exception Create(int hResult, string message)
        {
            return new ServiceContinueException((System.Exception)null, hResult, message);
        }
        /// <summary>
        /// Constructs the exception from an hresult and message bypassing the message formatting
        /// </summary>
        private ServiceContinueException(System.Exception innerException, int hResult, string message) : base(message, innerException)
        {
            base.HResult = hResult;
            base.HelpLink = $safeprojectname$.Resources.Exceptions.ExceptionStrings.HelpLinkFormat(HResult, GetType().FullName);
        }
        
        /// <summary>
        /// The serviceName parameter passed to the constructor
        /// </summary>
        public string ServiceName { get { if (Data["ServiceName"] is string) return (string)Data["ServiceName"]; else return default(string); } }
        
        /// <summary>
        /// The service {0} failed to resume correctly.
        /// </summary>
        public ServiceContinueException(string serviceName)
        	: this((System.Exception)null, unchecked((int)0xE1000006U), $safeprojectname$.Resources.Exceptions.ExceptionStrings.SafeFormat($safeprojectname$.Resources.Exceptions.ExceptionStrings.ServiceContinueException_string_ServiceName_, serviceName))
        {
            base.Data["ServiceName"] = serviceName;
            WriteEvent(serviceName);
        }
        /// <summary>
        /// The service {0} failed to resume correctly.
        /// </summary>
        public ServiceContinueException(string serviceName, System.Exception innerException)
        	: this(innerException, unchecked((int)0xE1000006U), $safeprojectname$.Resources.Exceptions.ExceptionStrings.SafeFormat($safeprojectname$.Resources.Exceptions.ExceptionStrings.ServiceContinueException_string_ServiceName_, serviceName))
        {
            base.Data["ServiceName"] = serviceName;
            WriteEvent(serviceName);
        }
        /// <summary>
        /// Prepares the arguments as strings and writes the event
        /// </summary>
        private void WriteEvent(string serviceName)
        {
            string[] ctorEventArguments = new string[] {
            $safeprojectname$.Resources.Exceptions.ExceptionStrings.SafeFormat(@"{0}", serviceName),
            };
            $safeprojectname$.Resources.Exceptions.WriteEvent(
                $safeprojectname$.Resources.Exceptions.EventLogName,
                $safeprojectname$.Resources.Exceptions.EventSourceName,
                $safeprojectname$.Resources.Exceptions.EventCategoryId,
                System.Diagnostics.EventLogEntryType.Error,
                0x0C1000006L, ctorEventArguments, this);
        }
        /// <summary>
        /// if(condition == false) throws The service {0} failed to resume correctly.
        /// </summary>
        public static void Assert(bool condition, string serviceName)
        {
            if (!condition) throw new ServiceContinueException(serviceName);
        }
    }
    /// <summary>
    /// Exception class: ServicePauseException
    /// The service {0} failed to pause correctly.
    /// </summary>
    [System.SerializableAttribute()]
    [global::System.Diagnostics.DebuggerStepThroughAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("CSharpTest.Net.Generators", "1.11.924.348")]
    public sealed partial class ServicePauseException : System.ApplicationException
    {
        /// <summary>
        /// Serialization constructor
        /// </summary>
        internal ServicePauseException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
        {
        }
        /// <summary>
        /// Used to create this exception from an hresult and message bypassing the message formatting
        /// </summary>
        internal static System.Exception Create(int hResult, string message)
        {
            return new ServicePauseException((System.Exception)null, hResult, message);
        }
        /// <summary>
        /// Constructs the exception from an hresult and message bypassing the message formatting
        /// </summary>
        private ServicePauseException(System.Exception innerException, int hResult, string message) : base(message, innerException)
        {
            base.HResult = hResult;
            base.HelpLink = $safeprojectname$.Resources.Exceptions.ExceptionStrings.HelpLinkFormat(HResult, GetType().FullName);
        }
        
        /// <summary>
        /// The serviceName parameter passed to the constructor
        /// </summary>
        public string ServiceName { get { if (Data["ServiceName"] is string) return (string)Data["ServiceName"]; else return default(string); } }
        
        /// <summary>
        /// The service {0} failed to pause correctly.
        /// </summary>
        public ServicePauseException(string serviceName)
        	: this((System.Exception)null, unchecked((int)0xE1000007U), $safeprojectname$.Resources.Exceptions.ExceptionStrings.SafeFormat($safeprojectname$.Resources.Exceptions.ExceptionStrings.ServicePauseException_string_ServiceName_, serviceName))
        {
            base.Data["ServiceName"] = serviceName;
            WriteEvent(serviceName);
        }
        /// <summary>
        /// The service {0} failed to pause correctly.
        /// </summary>
        public ServicePauseException(string serviceName, System.Exception innerException)
        	: this(innerException, unchecked((int)0xE1000007U), $safeprojectname$.Resources.Exceptions.ExceptionStrings.SafeFormat($safeprojectname$.Resources.Exceptions.ExceptionStrings.ServicePauseException_string_ServiceName_, serviceName))
        {
            base.Data["ServiceName"] = serviceName;
            WriteEvent(serviceName);
        }
        /// <summary>
        /// Prepares the arguments as strings and writes the event
        /// </summary>
        private void WriteEvent(string serviceName)
        {
            string[] ctorEventArguments = new string[] {
            $safeprojectname$.Resources.Exceptions.ExceptionStrings.SafeFormat(@"{0}", serviceName),
            };
            $safeprojectname$.Resources.Exceptions.WriteEvent(
                $safeprojectname$.Resources.Exceptions.EventLogName,
                $safeprojectname$.Resources.Exceptions.EventSourceName,
                $safeprojectname$.Resources.Exceptions.EventCategoryId,
                System.Diagnostics.EventLogEntryType.Error,
                0x0C1000007L, ctorEventArguments, this);
        }
        /// <summary>
        /// if(condition == false) throws The service {0} failed to pause correctly.
        /// </summary>
        public static void Assert(bool condition, string serviceName)
        {
            if (!condition) throw new ServicePauseException(serviceName);
        }
    }
    /// <summary>
    /// Exception class: ServiceCommandException
    /// The service {0} failed to process command #{1}.
    /// </summary>
    [System.SerializableAttribute()]
    [global::System.Diagnostics.DebuggerStepThroughAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("CSharpTest.Net.Generators", "1.11.924.348")]
    public sealed partial class ServiceCommandException : System.ApplicationException
    {
        /// <summary>
        /// Serialization constructor
        /// </summary>
        internal ServiceCommandException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
        {
        }
        /// <summary>
        /// Used to create this exception from an hresult and message bypassing the message formatting
        /// </summary>
        internal static System.Exception Create(int hResult, string message)
        {
            return new ServiceCommandException((System.Exception)null, hResult, message);
        }
        /// <summary>
        /// Constructs the exception from an hresult and message bypassing the message formatting
        /// </summary>
        private ServiceCommandException(System.Exception innerException, int hResult, string message) : base(message, innerException)
        {
            base.HResult = hResult;
            base.HelpLink = $safeprojectname$.Resources.Exceptions.ExceptionStrings.HelpLinkFormat(HResult, GetType().FullName);
        }
        
        /// <summary>
        /// The serviceName parameter passed to the constructor
        /// </summary>
        public string ServiceName { get { if (Data["ServiceName"] is string) return (string)Data["ServiceName"]; else return default(string); } }
        
        /// <summary>
        /// The commandId parameter passed to the constructor
        /// </summary>
        public int CommandId { get { if (Data["CommandId"] is int) return (int)Data["CommandId"]; else return default(int); } }
        
        /// <summary>
        /// The service {0} failed to process command #{1}.
        /// </summary>
        public ServiceCommandException(string serviceName, int commandId)
        	: this((System.Exception)null, unchecked((int)0xE1000008U), $safeprojectname$.Resources.Exceptions.ExceptionStrings.SafeFormat($safeprojectname$.Resources.Exceptions.ExceptionStrings.ServiceCommandException_string_ServiceName__int_CommandId_, serviceName, commandId))
        {
            base.Data["ServiceName"] = serviceName;
            base.Data["CommandId"] = commandId;
            WriteEvent(serviceName, commandId);
        }
        /// <summary>
        /// The service {0} failed to process command #{1}.
        /// </summary>
        public ServiceCommandException(string serviceName, int commandId, System.Exception innerException)
        	: this(innerException, unchecked((int)0xE1000008U), $safeprojectname$.Resources.Exceptions.ExceptionStrings.SafeFormat($safeprojectname$.Resources.Exceptions.ExceptionStrings.ServiceCommandException_string_ServiceName__int_CommandId_, serviceName, commandId))
        {
            base.Data["ServiceName"] = serviceName;
            base.Data["CommandId"] = commandId;
            WriteEvent(serviceName, commandId);
        }
        /// <summary>
        /// Prepares the arguments as strings and writes the event
        /// </summary>
        private void WriteEvent(string serviceName, int commandId)
        {
            string[] ctorEventArguments = new string[] {
            $safeprojectname$.Resources.Exceptions.ExceptionStrings.SafeFormat(@"{0}", serviceName),
            $safeprojectname$.Resources.Exceptions.ExceptionStrings.SafeFormat(@"{0}", commandId),
            };
            $safeprojectname$.Resources.Exceptions.WriteEvent(
                $safeprojectname$.Resources.Exceptions.EventLogName,
                $safeprojectname$.Resources.Exceptions.EventSourceName,
                $safeprojectname$.Resources.Exceptions.EventCategoryId,
                System.Diagnostics.EventLogEntryType.Error,
                0x0C1000008L, ctorEventArguments, this);
        }
        /// <summary>
        /// if(condition == false) throws The service {0} failed to process command #{1}.
        /// </summary>
        public static void Assert(bool condition, string serviceName, int commandId)
        {
            if (!condition) throw new ServiceCommandException(serviceName, commandId);
        }
    }
    /// <summary>
    /// Exception class: UnhandledException
    /// Unhandled exception: {0}
    /// </summary>
    [System.SerializableAttribute()]
    [global::System.Diagnostics.DebuggerStepThroughAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("CSharpTest.Net.Generators", "1.11.924.348")]
    public sealed partial class UnhandledException : System.ApplicationException
    {
        /// <summary>
        /// Serialization constructor
        /// </summary>
        internal UnhandledException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
        {
        }
        /// <summary>
        /// Used to create this exception from an hresult and message bypassing the message formatting
        /// </summary>
        internal static System.Exception Create(int hResult, string message)
        {
            return new UnhandledException((System.Exception)null, hResult, message);
        }
        /// <summary>
        /// Constructs the exception from an hresult and message bypassing the message formatting
        /// </summary>
        private UnhandledException(System.Exception innerException, int hResult, string message) : base(message, innerException)
        {
            base.HResult = hResult;
            base.HelpLink = $safeprojectname$.Resources.Exceptions.ExceptionStrings.HelpLinkFormat(HResult, GetType().FullName);
        }
        /// <summary>
        /// Unhandled exception: {0}
        /// </summary>
        public UnhandledException(string message)
        	: this((System.Exception)null, unchecked((int)0xE100000BU), $safeprojectname$.Resources.Exceptions.ExceptionStrings.SafeFormat($safeprojectname$.Resources.Exceptions.ExceptionStrings.UnhandledException_string_message_, message))
        {
            WriteEvent(message);
        }
        /// <summary>
        /// Unhandled exception: {0}
        /// </summary>
        public UnhandledException(string message, System.Exception innerException)
        	: this(innerException, unchecked((int)0xE100000BU), $safeprojectname$.Resources.Exceptions.ExceptionStrings.SafeFormat($safeprojectname$.Resources.Exceptions.ExceptionStrings.UnhandledException_string_message_, message))
        {
            WriteEvent(message);
        }
        /// <summary>
        /// Prepares the arguments as strings and writes the event
        /// </summary>
        private void WriteEvent(string message)
        {
            string[] ctorEventArguments = new string[] {
            $safeprojectname$.Resources.Exceptions.ExceptionStrings.SafeFormat(@"{0}", message),
            };
            $safeprojectname$.Resources.Exceptions.WriteEvent(
                $safeprojectname$.Resources.Exceptions.EventLogName,
                $safeprojectname$.Resources.Exceptions.EventSourceName,
                $safeprojectname$.Resources.Exceptions.EventCategoryId,
                System.Diagnostics.EventLogEntryType.Error,
                0x0C100000BL, ctorEventArguments, this);
        }
        /// <summary>
        /// if(condition == false) throws Unhandled exception: {0}
        /// </summary>
        public static void Assert(bool condition, string message)
        {
            if (!condition) throw new UnhandledException(message);
        }
    }


}

