//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.Resources
{
    using System;
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This partial class was auto-generated by the StronglyTypedResourceBuilder
    // partial class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class FormatString
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormatString()
        {
        }
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("$safeprojectname$.Resources.FormatString", typeof(FormatString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to The service failed to execute the command..
        /// </summary>
        public static string CommandFailedMessage
        {
            get
            {
                return ResourceManager.GetString("CommandFailedMessage", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to CommandID.
        /// </summary>
        public static string CommandID
        {
            get
            {
                return ResourceManager.GetString("CommandID", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to The timeout expired while waiting for the service..
        /// </summary>
        public static string CommandTimeoutMessage
        {
            get
            {
                return ResourceManager.GetString("CommandTimeoutMessage", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Missing required argument..
        /// </summary>
        public static string MissingRequiredArgument
        {
            get
            {
                return ResourceManager.GetString("MissingRequiredArgument", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Press [Enter] to exit....
        /// </summary>
        public static string PressEnterToExit
        {
            get
            {
                return ResourceManager.GetString("PressEnterToExit", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ServiceName.
        /// </summary>
        public static string ServiceName
        {
            get
            {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Starting the service....
        /// </summary>
        public static string StartingService
        {
            get
            {
                return ResourceManager.GetString("StartingService", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Stopping the service....
        /// </summary>
        public static string StoppingService
        {
            get
            {
                return ResourceManager.GetString("StoppingService", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to The service did not respond..
        /// </summary>
        public static string UnableToControlService
        {
            get
            {
                return ResourceManager.GetString("UnableToControlService", resourceCulture);
            }
        }
  

        /// <summary>
        /// The value for must be between {0} and {1}.
        /// </summary>
        public static string ArgumentOutOfRange(object _0, object _1)
        {
            return String.Format(resourceCulture, $safeprojectname$.Resources.FormatString.FormatStrings.ArgumentOutOfRange, _0, _1);
        }
        /// <summary>
        /// Global\{0}.Command.{1}.Failure
        /// </summary>
        public static string CommandFailureSignal(string name, int id)
        {
            return String.Format(resourceCulture, $safeprojectname$.Resources.FormatString.FormatStrings.CommandFailureSignal_string_name__int_id_, name, id);
        }
        /// <summary>
        /// Global\{0}.Command.{1}.Success
        /// </summary>
        public static string CommandSuccessSignal(string name, int id)
        {
            return String.Format(resourceCulture, $safeprojectname$.Resources.FormatString.FormatStrings.CommandSuccessSignal_string_name__int_id_, name, id);
        }
        /// <summary>
        /// Invalid argument value: '{0}'.
        /// </summary>
        public static string InvalidArgumentValue(object _0)
        {
            return String.Format(resourceCulture, $safeprojectname$.Resources.FormatString.FormatStrings.InvalidArgumentValue, _0);
        }
        /// <summary>
        /// Global\{0}.Command.{1}.Lock
        /// </summary>
        public static string ServiceCommandLock(string name, int id)
        {
            return String.Format(resourceCulture, $safeprojectname$.Resources.FormatString.FormatStrings.ServiceCommandLock_string_name__int_id_, name, id);
        }
        
        /// <summary>
        /// Returns the raw format strings.
        /// </summary>
        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("CSharpTest.Net.Generators", "1.11.924.348")]
        public static partial class FormatStrings
        {
            /// <summary>
            /// The value for must be between {0} and {1}.
            /// </summary>
            public static string ArgumentOutOfRange { get { return ResourceManager.GetString("ArgumentOutOfRange", resourceCulture); } }
            /// <summary>
            /// Global\{0}.Command.{1}.Failure
            /// </summary>
            public static string CommandFailureSignal_string_name__int_id_ { get { return ResourceManager.GetString("CommandFailureSignal(string name, int id)", resourceCulture); } }
            /// <summary>
            /// Global\{0}.Command.{1}.Success
            /// </summary>
            public static string CommandSuccessSignal_string_name__int_id_ { get { return ResourceManager.GetString("CommandSuccessSignal(string name, int id)", resourceCulture); } }
            /// <summary>
            /// Invalid argument value: '{0}'.
            /// </summary>
            public static string InvalidArgumentValue { get { return ResourceManager.GetString("InvalidArgumentValue", resourceCulture); } }
            /// <summary>
            /// Global\{0}.Command.{1}.Lock
            /// </summary>
            public static string ServiceCommandLock_string_name__int_id_ { get { return ResourceManager.GetString("ServiceCommandLock(string name, int id)", resourceCulture); } }
        }
    
     }



}

