//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.Resources
{
    using System;
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This partial class was auto-generated by the StronglyTypedResourceBuilder
    // partial class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Messages
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages()
        {
        }
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("$safeprojectname$.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
  

        
        /// <summary>
        /// Create the appropriate type of exception from an hresult using the specified message
        /// </summary>
        public static bool TryCreateException(int hResult, string message, out System.Exception exception)
        {
            switch (unchecked((uint)hResult))
            {
                default: exception = null; return false;
            }
        }
        
        /// <summary>
        /// The the event log facility id of events defined in this resource file
        /// </summary>
        internal static readonly int EventFacilityId = 256;
        
        /// <summary>
        /// The category id used to write events for this resource file
        /// </summary>
        internal static readonly int EventCategoryId = 1;
        
        /// <summary>
        /// The the event log used to write events for this resource file
        /// </summary>
        internal static readonly string EventLogName = "$safeprojectname$";
        
        /// <summary>
        /// The event source used to write events
        /// </summary>
        internal static readonly string EventSourceName = "$safeprojectname$";
        
        /// <summary>
        /// Writes an event log for the specified message id and arguments
        /// </summary>
        internal static void WriteEvent(string eventLog, string eventSource, int category, System.Diagnostics.EventLogEntryType eventType, long eventId, object[] arguments, System.Exception error)
        {
            try
            {
                EventLogging.WriteEvent(eventLog, eventSource, category, eventType, eventId, arguments, error);
            }
            catch { }
        }
        /// <summary>
        /// The service {0} started successfully.
        /// </summary>
        public static string ServiceStarted(string serviceName)
        {
            string[] ctorEventArguments = new string[] {
            String.Format(@"{0}", serviceName),
            };
            $safeprojectname$.Resources.Messages.WriteEvent(
                $safeprojectname$.Resources.Messages.EventLogName,
                $safeprojectname$.Resources.Messages.EventSourceName,
                $safeprojectname$.Resources.Messages.EventCategoryId,
                System.Diagnostics.EventLogEntryType.Information,
                0x041000002L, ctorEventArguments, null);
            return String.Format(resourceCulture, $safeprojectname$.Resources.Messages.FormatStrings.ServiceStarted_string_ServiceName_, serviceName);
        }
        /// <summary>
        /// The service {0} has stopped.
        /// </summary>
        public static string ServiceStopped(string serviceName)
        {
            string[] ctorEventArguments = new string[] {
            String.Format(@"{0}", serviceName),
            };
            $safeprojectname$.Resources.Messages.WriteEvent(
                $safeprojectname$.Resources.Messages.EventLogName,
                $safeprojectname$.Resources.Messages.EventSourceName,
                $safeprojectname$.Resources.Messages.EventCategoryId,
                System.Diagnostics.EventLogEntryType.Information,
                0x041000003L, ctorEventArguments, null);
            return String.Format(resourceCulture, $safeprojectname$.Resources.Messages.FormatStrings.ServiceStopped_string_ServiceName_, serviceName);
        }
        /// <summary>
        /// The service {0} has been paused.
        /// </summary>
        public static string ServicePaused(string serviceName)
        {
            string[] ctorEventArguments = new string[] {
            String.Format(@"{0}", serviceName),
            };
            $safeprojectname$.Resources.Messages.WriteEvent(
                $safeprojectname$.Resources.Messages.EventLogName,
                $safeprojectname$.Resources.Messages.EventSourceName,
                $safeprojectname$.Resources.Messages.EventCategoryId,
                System.Diagnostics.EventLogEntryType.Information,
                0x041000009L, ctorEventArguments, null);
            return String.Format(resourceCulture, $safeprojectname$.Resources.Messages.FormatStrings.ServicePaused_string_ServiceName_, serviceName);
        }
        /// <summary>
        /// The service {0} has resumed.
        /// </summary>
        public static string ServiceResumed(string serviceName)
        {
            string[] ctorEventArguments = new string[] {
            String.Format(@"{0}", serviceName),
            };
            $safeprojectname$.Resources.Messages.WriteEvent(
                $safeprojectname$.Resources.Messages.EventLogName,
                $safeprojectname$.Resources.Messages.EventSourceName,
                $safeprojectname$.Resources.Messages.EventCategoryId,
                System.Diagnostics.EventLogEntryType.Information,
                0x04100000AL, ctorEventArguments, null);
            return String.Format(resourceCulture, $safeprojectname$.Resources.Messages.FormatStrings.ServiceResumed_string_ServiceName_, serviceName);
        }
        /// <summary>
        /// Unhandled exception: {0}
        /// </summary>
        public static string UnhandledError(string message, System.Exception error)
        {
            string[] ctorEventArguments = new string[] {
            String.Format(@"{0}", message),
            String.Format(@"{0}", error),
            };
            $safeprojectname$.Resources.Messages.WriteEvent(
                $safeprojectname$.Resources.Messages.EventLogName,
                $safeprojectname$.Resources.Messages.EventSourceName,
                $safeprojectname$.Resources.Messages.EventCategoryId,
                System.Diagnostics.EventLogEntryType.Error,
                0x0C100000CL, ctorEventArguments, null);
            return String.Format(resourceCulture, $safeprojectname$.Resources.Messages.FormatStrings.UnhandledError_string_message__System_Exception_error_, message, error);
        }
        /// <summary>
        /// The service {0} failed processing session event {1} for session {2}: {3}
        /// </summary>
        public static string ServiceSessionChangeError(string serviceName, System.ServiceProcess.SessionChangeReason reason, int sessionId, string message, System.Exception error)
        {
            string[] ctorEventArguments = new string[] {
            String.Format(@"{0}", serviceName),
            String.Format(@"{0}", reason),
            String.Format(@"{0}", sessionId),
            String.Format(@"{0}", message),
            String.Format(@"{0}", error),
            };
            $safeprojectname$.Resources.Messages.WriteEvent(
                $safeprojectname$.Resources.Messages.EventLogName,
                $safeprojectname$.Resources.Messages.EventSourceName,
                $safeprojectname$.Resources.Messages.EventCategoryId,
                System.Diagnostics.EventLogEntryType.Warning,
                0x08100000EL, ctorEventArguments, null);
            return String.Format(resourceCulture, $safeprojectname$.Resources.Messages.FormatStrings.ServiceSessionChangeError_string_ServiceName__System_ServiceProcess_SessionChangeReason_Reason__int_SessionId__string_Message__System_Exception_error_, serviceName, reason, sessionId, message, error);
        }
        /// <summary>
        /// The service {0} failed processing power event {1}: {2}
        /// </summary>
        public static string ServicePowerEventError(string serviceName, System.ServiceProcess.PowerBroadcastStatus eventType, string message, System.Exception error)
        {
            string[] ctorEventArguments = new string[] {
            String.Format(@"{0}", serviceName),
            String.Format(@"{0}", eventType),
            String.Format(@"{0}", message),
            String.Format(@"{0}", error),
            };
            $safeprojectname$.Resources.Messages.WriteEvent(
                $safeprojectname$.Resources.Messages.EventLogName,
                $safeprojectname$.Resources.Messages.EventSourceName,
                $safeprojectname$.Resources.Messages.EventCategoryId,
                System.Diagnostics.EventLogEntryType.Warning,
                0x08100000DL, ctorEventArguments, null);
            return String.Format(resourceCulture, $safeprojectname$.Resources.Messages.FormatStrings.ServicePowerEventError_string_ServiceName__System_ServiceProcess_PowerBroadcastStatus_EventType__string_Message__System_Exception_error_, serviceName, eventType, message, error);
        }
        /// <summary>
        /// Service warning from {0}: {1}
        /// </summary>
        public static string Warning(string serviceName, string message)
        {
            string[] ctorEventArguments = new string[] {
            String.Format(@"{0}", serviceName),
            String.Format(@"{0}", message),
            };
            $safeprojectname$.Resources.Messages.WriteEvent(
                $safeprojectname$.Resources.Messages.EventLogName,
                $safeprojectname$.Resources.Messages.EventSourceName,
                $safeprojectname$.Resources.Messages.EventCategoryId,
                System.Diagnostics.EventLogEntryType.Warning,
                0x08100000FL, ctorEventArguments, null);
            return String.Format(resourceCulture, $safeprojectname$.Resources.Messages.FormatStrings.Warning_string_ServiceName__string_message_, serviceName, message);
        }
        /// <summary>
        /// Service warning from {0}: {1}
        /// </summary>
        public static string Warning(string serviceName, string message, System.Exception error)
        {
            string[] ctorEventArguments = new string[] {
            String.Format(@"{0}", serviceName),
            String.Format(@"{0}", message),
            String.Format(@"{0}", error),
            };
            $safeprojectname$.Resources.Messages.WriteEvent(
                $safeprojectname$.Resources.Messages.EventLogName,
                $safeprojectname$.Resources.Messages.EventSourceName,
                $safeprojectname$.Resources.Messages.EventCategoryId,
                System.Diagnostics.EventLogEntryType.Warning,
                0x081000010L, ctorEventArguments, null);
            return String.Format(resourceCulture, $safeprojectname$.Resources.Messages.FormatStrings.Warning_string_ServiceName__string_message__System_Exception_error_, serviceName, message, error);
        }
        /// <summary>
        /// The service {0} recieved command {1}.
        /// </summary>
        public static string ServiceCommand(string serviceName, int command)
        {
            string[] ctorEventArguments = new string[] {
            String.Format(@"{0}", serviceName),
            String.Format(@"{0}", command),
            };
            $safeprojectname$.Resources.Messages.WriteEvent(
                $safeprojectname$.Resources.Messages.EventLogName,
                $safeprojectname$.Resources.Messages.EventSourceName,
                $safeprojectname$.Resources.Messages.EventCategoryId,
                System.Diagnostics.EventLogEntryType.Information,
                0x041000011L, ctorEventArguments, null);
            return String.Format(resourceCulture, $safeprojectname$.Resources.Messages.FormatStrings.ServiceCommand_string_ServiceName__int_command_, serviceName, command);
        }
        
        /// <summary>
        /// Returns the raw format strings.
        /// </summary>
        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("CSharpTest.Net.Generators", "1.11.924.348")]
        public static partial class FormatStrings
        {
            /// <summary>
            /// The service {0} started successfully.
            /// </summary>
            public static string ServiceStarted_string_ServiceName_ { get { return ResourceManager.GetString("ServiceStarted(string ServiceName)", resourceCulture); } }
            /// <summary>
            /// The service {0} has stopped.
            /// </summary>
            public static string ServiceStopped_string_ServiceName_ { get { return ResourceManager.GetString("ServiceStopped(string ServiceName)", resourceCulture); } }
            /// <summary>
            /// The service {0} has been paused.
            /// </summary>
            public static string ServicePaused_string_ServiceName_ { get { return ResourceManager.GetString("ServicePaused(string ServiceName)", resourceCulture); } }
            /// <summary>
            /// The service {0} has resumed.
            /// </summary>
            public static string ServiceResumed_string_ServiceName_ { get { return ResourceManager.GetString("ServiceResumed(string ServiceName)", resourceCulture); } }
            /// <summary>
            /// Unhandled exception: {0}
            /// </summary>
            public static string UnhandledError_string_message__System_Exception_error_ { get { return ResourceManager.GetString("UnhandledError(string message, System.Exception error)", resourceCulture); } }
            /// <summary>
            /// The service {0} failed processing session event {1} for session {2}: {3}
            /// </summary>
            public static string ServiceSessionChangeError_string_ServiceName__System_ServiceProcess_SessionChangeReason_Reason__int_SessionId__string_Message__System_Exception_error_ { get { return ResourceManager.GetString("ServiceSessionChangeError(string ServiceName, System.ServiceProcess.SessionChangeReason Reason, int SessionId, string Message, System.Exception error)", resourceCulture); } }
            /// <summary>
            /// The service {0} failed processing power event {1}: {2}
            /// </summary>
            public static string ServicePowerEventError_string_ServiceName__System_ServiceProcess_PowerBroadcastStatus_EventType__string_Message__System_Exception_error_ { get { return ResourceManager.GetString("ServicePowerEventError(string ServiceName, System.ServiceProcess.PowerBroadcastStatus EventType, string Message, System.Exception error)", resourceCulture); } }
            /// <summary>
            /// Service warning from {0}: {1}
            /// </summary>
            public static string Warning_string_ServiceName__string_message_ { get { return ResourceManager.GetString("Warning(string ServiceName, string message)", resourceCulture); } }
            /// <summary>
            /// Service warning from {0}: {1}
            /// </summary>
            public static string Warning_string_ServiceName__string_message__System_Exception_error_ { get { return ResourceManager.GetString("Warning(string ServiceName, string message, System.Exception error)", resourceCulture); } }
            /// <summary>
            /// The service {0} recieved command {1}.
            /// </summary>
            public static string ServiceCommand_string_ServiceName__int_command_ { get { return ResourceManager.GetString("ServiceCommand(string ServiceName, int command)", resourceCulture); } }
        }
    
     }



}

